In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('89d88c5528513adc4002a1618ce2efb0_iris.csv')
df

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [ ]:
df.shape

(149, 5)

In [ ]:
df.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [ ]:
df.columns=[0,1,2,3,4]
df

0    1    2    3               4
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [ ]:
df[5].value_counts()#to count different kind of species

NameError: ignored

In [ ]:
x=df.iloc[: , :4]#to seperate depenedent and independent features
y=df.iloc[:, 4]
print("X:\n...........\n{}".format(x))
print("X:\n...........\n{}".format(y))

X:
...........
       0    1    2    3
0    4.9  3.0  1.4  0.2
1    4.7  3.2  1.3  0.2
2    4.6  3.1  1.5  0.2
3    5.0  3.6  1.4  0.2
4    5.4  3.9  1.7  0.4
..   ...  ...  ...  ...
144  6.7  3.0  5.2  2.3
145  6.3  2.5  5.0  1.9
146  6.5  3.0  5.2  2.0
147  6.2  3.4  5.4  2.3
148  5.9  3.0  5.1  1.8

[149 rows x 4 columns]
X:
...........
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
Name: 4, Length: 149, dtype: object


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,random_state=0)
print("X_train:\n{}".format(X_train))

X_train:
       0    1    2    3
51   6.9  3.1  4.9  1.5
2    4.6  3.1  1.5  0.2
146  6.5  3.0  5.2  2.0
10   4.8  3.4  1.6  0.2
56   4.9  2.4  3.3  1.0
..   ...  ...  ...  ...
9    5.4  3.7  1.5  0.2
103  6.5  3.0  5.8  2.2
67   6.2  2.2  4.5  1.5
117  7.7  2.6  6.9  2.3
47   5.3  3.7  1.5  0.2

[111 rows x 4 columns]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,Y_train)
y_pred=knn.predict(X_test)
print(y_pred)#machine predicted target
print("Y_test:\n{}".format(Y_test))#original target

['Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor']
Y_test:
133     Iris-virginica
109     Iris-virginica
59     Iris-versicolor
80     Iris-versicolor
7          Iris-setosa
104     Iris-virginica
140     Iris-virginica
95     Iris-versicolor
118     Iris-virginica
84     Iris-versicolor
33         Iris-setosa
44         Iris-setosa
54     Iris-versicolor
24         Iris-setosa
37         Iris-setosa
132     Iris-vir

In [ ]:
#as the above output is difficult to compare
#we use confusion matrix
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(Y_test,y_pred))
accuracy=accuracy_score(Y_test,y_pred)*100
print("accuracy of the model is {:.2f}".format(accuracy))

[[14  0  0]
 [ 0 13  1]
 [ 0  3  7]]
accuracy of the model is 89.47


In [ ]:
#finding the target name for the given feature
X_new=np.array([[151,2.3,2.9,5.0]])
print("X_new.shape:{}".format(X_new.shape))
y_new=knn.predict(X_new)
print("prediction \n{}".format(y_new))

X_new.shape:(1, 4)
prediction 
['Iris-virginica']
